autoSyncfile: sync.yaml
workDir: "./workdir"
syncedDir: "./images"
# 设置为true则只生成同步后的文件，正常同步应该设置为false
genSynced: false
regexp: '(alpha|beta|rc|amd64|ppc64le|arm64|arm|s390x|SNAPSHOT|snapshot|debug|master|latest|main|sig|sha|mips|server|nanoserver|windows|build|HEAD|unstable|dev|test|\.sig|canary|enterprise)'
images:
  docker.io:
    - library/alpine
    - eniz1806/vaults3
  ghcr.io:
    - authelia/authelia
  #   - grafana/alloy
  #   - grafana/grafana
  #   - grafana/loki
  #   - kiwigrid/k8s-sidecar
  # quay.io:
  #   - prometheus-operator/prometheus-config-reloader
  #   - prometheus/node-exporter
  #   - prometheus/prometheus
  # registry.k8s.io:
  #   - kube-state-metrics/kube-state-metrics  
  
