autoSyncfile: sync.yaml
workDir: "./workdir"
syncedDir: "./images"
# 设置为true则只生成同步后的文件，正常同步应该设置为false
genSynced: false
regexp: '(alpha|beta|rc|amd64|ppc64le|arm64|arm|s390x|SNAPSHOT|snapshot|debug|master|latest|main|sig|sha|mips|server|nanoserver|windows|build|HEAD|unstable|dev|test|\.sig|canary|enterprise)'
images:
  docker.io:
    - istio/proxyv2
    - istio/pilot
    - library/redis
  quay.io:
    - argoproj/argocd
  ghcr.io:
    - dexidp/dex