# ***********************************************************************
# Description   : Blue Planet
# Author        : serialt
# Email         : tserialt@gmail.com
# Created Time  : 2023-02-16 23:45:27
# Last modified : 2024-03-02 08:33:31
# FilePath      : /sync-image/.github/workflows/sync.yml
# Other         : 
#               : 
# 
#                 人和代码，有一个能跑就行
# 
# ***********************************************************************
name: sync

on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 3 */3 * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go 
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.23.0'
    - name: Install dependencies
      run: |
        export version=v1.13.3 && export  arch=amd64 && sudo wget https://github.com/serialt/skopeo/releases/download/${version}/skopeo-linux-${arch} -O /usr/bin/skopeo && sudo chmod +x /usr/bin/skopeo
        skopeo --version
        go mod tidy
        go install .
    - name: sync-image
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        HUB_USERNAME: ${{ secrets.HUB_USERNAME }}
        HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
        HUB_URL: ${{ secrets.HUB_URL }}
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        sync-image

